### ISSUE TITLE
commercial titles (under searcher pricing) need to have a button that says "quoted" so searchers can list that they quote commercial searches

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#60] opened 2019-05-23 11:39 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by PendragonDevelopment** [comment] 2019-05-23 12:42
Duplicate of #57

**Closed** 2019-06-02 18:54 UTC
Labels: duplicate
