### ISSUE TITLE
cant see products on next screen per screen shot

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#61] opened 2019-05-23 11:46 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
![product details](https://user-images.githubusercontent.com/43005119/58250220-e8403380-7d2e-11e9-8038-4205c25ec18d.png)

**Comment by PendragonDevelopment** [comment] 2019-05-23 12:41
This is a duplicate of #44.

**Closed** 2019-06-02 18:54 UTC
Labels: duplicate
