### ISSUE TITLE
insurance

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#113] opened 2019-06-11 19:29 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
![insurance1](https://user-images.githubusercontent.com/43005119/59300630-a59eb680-8c5d-11e9-9557-adc280385bc3.png)

**Comment by PendragonDevelopment** [comment] 2019-06-18 23:46
Duplicate of #93

**Closed by PendragonDevelopment** 2019-06-18 23:46 UTC
